version: '3'
services:

  jenkins:
    build: './jenkins'
    networks:
      - jenkins
    ports:
      - '8080:8080'
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:

networks:
  jenkins:

